# Generated by Django 4.2.2 on 2023-06-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('mobno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=20)),
                ('ctc', models.CharField(max_length=20)),
            ],
        ),
    ]
